### ISSUE TITLE
サーバーエラー（KeyError）が発生する場合がある

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#112]
### エラー内容
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/src/pres_note/config/utils.py", line 71, in custom_exception_handler
    response.data.pop('messages')
KeyError: 'messages'
```

### エラー画面
![image](https://user-images.githubusercontent.com/5554576/109263156-1d53b100-7846-11eb-970f-b04c8007a3d6.png)

**Comment by namkim** [comment]
板倉さんが対応中
