### ISSUE TITLE
モデル作成

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#16]
### モデル
 - [ ] study 研究
 - [ ] experiment 実験
 - [ ] experiment_history 実験履歴
 - [ ] experiment_folder 実験フォルダー
 - [ ] study_folder 研究フォルダー
 - [ ] reference 参考資料
 - [ ] users ユーザーデータ
 - [ ] laboratory 研究室
 - [ ] experiment_approval 実験承認設定マスタ

**Comment by namkim** [comment]
https://docs.google.com/spreadsheets/d/1ts5grlxBnaBG_z_hF2zk71e-hbfkmGbcHJI8iqV2DC8/edit#gid=697439846

**Comment by namkim** [comment]
テーブル名などを、修正しました。

**Comment by namkim** [comment]
メモ
migrateでエラー
```
root@c3c81b5f3ec9:/src/pres_note# python manage.py migrate --fake study zero
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/pres_note/study/models.py", line 2, in <module>
    from experiment.models import ExperimentApproval
  File "/src/pres_note/experiment/models.py", line 2, in <module>
    from study.models import StudyLaboratory, Study, StudyFolder
ImportError: cannot import name 'StudyLaboratory' from 'study.models' (/src/pres_note/study/models.py)
```

**Comment by t-itakura** [comment]
migrateエラーについて  

依存関係に誤りがある場合
カスタムuserを使うとこのようなエラーメッセージが表示されることがある。
エラーを解消するにはadminをmigrateさせないこと。
```
pres-web-api | django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency users.0001_initial on database 'default'.
```

1. settings.pyのINSTALLED_APPSから'django.contrib.admin',をコメントアウト
2. configディレクトリのurls.pyからadmin/のルーティングをコメントアウト
3. マイグレーション後に1,2のコメントアウト箇所を戻す

**Comment by t-itakura** [comment]
study modelの修正
```
before
mysql> desc study_study;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int(11)      | NO   | PRI | NULL    | auto_increment |
| study_title          | longtext     | YES  |     | NULL    |                |
| study_responsibility | varchar(255) | YES  |     | NULL    |                |
| study_manager        | varchar(255) | YES  |     | NULL    |                |
| created_at           | datetime(6)  | YES  |     | NULL    |                |
| updated_at           | datetime(6)  | YES  |     | NULL    |                |
| end_at               | datetime(6)  | YES  |     | NULL    |                |
| operator             | varchar(255) | YES  |     | NULL    |                |
| laboratory_id        | int(11)      | NO   | MUL | NULL    |                |
| study_folder_id      | int(11)      | NO   | MUL | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
10 rows in set (0.00 sec)

after
mysql> desc study_study;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int(11)      | NO   | PRI | NULL    | auto_increment |
| study_title          | longtext     | YES  |     | NULL    |                |
| study_responsibility | varchar(255) | YES  |     | NULL    |                |
| created_at           | datetime(6)  | YES  |     | NULL    |                |
| updated_at           | datetime(6)  | YES  |     | NULL    |                |
| end_at               | datetime(6)  | YES  |     | NULL    |                |
| operator_id          | int(11)      | NO   | MUL | NULL    |                |
| laboratory_id        | int(11)      | NO   | MUL | NULL    |                |
| study_folder_id      | int(11)      | NO   | MUL | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
```

**Comment by t-itakura** [comment]
モデル修正の続き
