### ISSUE TITLE
テストデータの準備

### ISSUE THREAD

**Issue by t-itakura** [pres-inc/pres-paper#20]
#16 
モデルのfixtureも準備します
- [ ]  study 研究
- [ ]  experiment 実験
- [ ]  experiment_history 実験履歴
- [ ]  experiment_folder 実験フォルダー
- [ ]  study_folder 研究フォルダー
- [ ]  reference 参考資料
- [ ]  users ユーザーデータ
- [ ]  laboratory 研究室
- [ ]  experiment_approval 実験承認設定マスタ

**Comment by t-itakura** [comment]
test_tableで確認してみる 
```
python manage.py loaddata test_table.json
```

エラーメッセージ  
```
root@efa2830dafed:/src/pres_note# python manage.py loaddata test_table.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 178, in get_model
    return self.models[model_name.lower()]
KeyError: 'test_table'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/python.py", line 153, in _get_model
    return apps.get_model(model_identifier)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 211, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 181, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'connection' doesn't have a 'test_table' model.
```

**Comment by t-itakura** [comment]
以下のように設定する  
```
[
    {
        "model": "connection.testtable",
        "pk": 1,
        "fields": {
            "name": "111",
            "created_at": "2020-12-01T00:00:00Z",
            "updated_at": "2020-12-01T00:00:00Z"
        }
    },
    {
        "model": "connection.testtable",
        "pk": 2,
        "fields": {
            "name": "222",
            "created_at": "2020-12-02T00:00:00Z",
            "updated_at": "2020-12-02T00:00:00Z"
        }
    },
    {
        "model": "connection.testtable",
        "pk": 3,
        "fields": {
            "name": "333",
            "created_at": "2020-12-03T00:00:00Z",
            "updated_at": "2020-12-03T00:00:00Z"
        }
    },
    {
        "model": "connection.testtable",
        "pk": 4,
        "fields": {
            "name": "444",
            "created_at": "2020-12-04T00:00:00Z",
            "updated_at": "2020-12-04T00:00:00Z"
        }
    },
    {
        "model": "connection.testtable",
        "pk": 5,
        "fields": {
            "name": "555",
            "created_at": "2020-12-05T00:00:00Z",
            "updated_at": "2020-12-05T00:00:00Z"
        }
    }
]
```

**Comment by t-itakura** [comment]
投入されたデータ  
```
mysql> select * from test_table;
+----+------+---------------------+---------------------+
| id | name | created_at          | updated_at          |
+----+------+---------------------+---------------------+
|  1 | 111  | 2020-12-01 00:00:00 | 2020-12-01 00:00:00 |
|  2 | 222  | 2020-12-02 00:00:00 | 2020-12-02 00:00:00 |
|  3 | 333  | 2020-12-03 00:00:00 | 2020-12-03 00:00:00 |
|  4 | 444  | 2020-12-04 00:00:00 | 2020-12-04 00:00:00 |
|  5 | 555  | 2020-12-05 00:00:00 | 2020-12-05 00:00:00 |
+----+------+---------------------+---------------------+
5 rows in set (0.00 sec)
```

**Comment by t-itakura** [comment]
実行のたびに洗い替えでデータを投入してくれる  
これでテストケースを作るのがいいかも知れない。  
実行コマンド  
```
python manage.py loaddata connection/fixtures/test_table.json
```

**Comment by t-itakura** [comment]
検証終了したので、こちらのモデルをマージ
残りのデータを作っていく
https://github.com/pres-inc/pres-paper/pull/19

**Comment by t-itakura** [comment]
テーブルに日本語のデータをインサートできない事象について

- まだ試していないけど manage.py loaddata でjsonに日本語が入っているとエラー
- insertクエリでテーブルに日本語データ入れよとしたけど空になっていた

```
mysql> select * from laboratory_laboratory where laboratory_name is null;
Empty set (0.00 sec)

mysql> select * from laboratory_laboratory where laboratory_name = '';
+----+-----------------+------------------------+------------+------------+------------+
| id | laboratory_name | experiment_approval_id | created_at | updated_at | deleted_at |
+----+-----------------+------------------------+------------+------------+------------+
|  4 |                 |                      0 | NULL       | NULL       | NULL       |
+----+-----------------+------------------------+------------+------------+------------+
```

**Comment by t-itakura** [comment]
日本語が入力できないのはmysqlの問題
```
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	latin1
Conn.  characterset:	latin1
```

ここの文字コードを変更する必要がある

**Comment by t-itakura** [comment]
```
mysql> SHOW VARIABLES LIKE 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | latin1                     |
| character_set_connection | latin1                     |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | latin1                     |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
```

**Comment by t-itakura** [comment]
my.cnf変更後
```
mysql> SHOW VARIABLES LIKE 'char%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | utf8                       |
| character_set_filesystem | utf8                       |
| character_set_results    | utf8                       |
| character_set_server     | utf8                       |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)
```

**Comment by t-itakura** [comment]
そもそもdockerimageのサーバーの問題じゃないか

**Comment by t-itakura** [comment]
サーバーのlocalに違いがある！
apiサーバー
```
root@ba0b8e75b156:/# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

dbサーバー
```
root@c3576bc90f3f:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by t-itakura** [comment]
Dockerfileを開発環境db向けに作成
うまく日本語を入力できた
```
root@a35940644818:/# locale
LANG=ja_JP.UTF-8
LANGUAGE=ja_JP:ja
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=ja_JP.UTF-8
root@a35940644818:/# あいうえお;
bash: あいうえお: command not found
```

mysqlにも日本語をインサートできた
```
mysql> INSERT INTO test_table (id,name) VALUES(5,'あああああ');
Query OK, 1 row affected (0.00 sec)

mysql> select * from test_table;
+----+-----------------+---------------------+---------------------+
| id | name            | created_at          | updated_at          |
+----+-----------------+---------------------+---------------------+
|  1 | test1           | 2020-12-17 18:36:51 | 2020-12-17 18:36:51 |
|  2 | test2           | 2020-12-17 18:36:51 | 2020-12-17 18:36:51 |
|  3 | test3           | 2020-12-17 18:36:51 | 2020-12-17 18:36:51 |
|  5 | あああああ      | 2020-12-17 18:38:29 | 2020-12-17 18:38:29 |
+----+-----------------+---------------------+---------------------+
4 rows in set (0.00 sec)
```
