### ISSUE TITLE
Experimentの作成でエラー

### ISSUE THREAD

**Issue by namkim** [pres-inc/pres-paper#88]
Experimaneのpostで作成する際、signalの方で、エラーが発生する

### POST画面
![image](https://user-images.githubusercontent.com/5554576/107194194-13067a00-6a33-11eb-81ee-8c12153df74b.png)

エラー内容
```
  File "/src/pres_note/experiment/signals.py", line 21, in wrapper
    signal_handler(*args, **kwargs)
  File "/src/pres_note/experiment/signals.py", line 35, in experiment_history_insert_hundler
    history.save()
  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 178, in save
    'You cannot call `.save()` on a serializer with invalid data.'
AssertionError: You cannot call `.save()` on a serializer with invalid data.
```

### その他
基本的な、　GET,POST,UPDATEなどは、テストパタンを作った方がいいかもですね。

**Comment by namkim** [comment]
```
======================================================================
FAIL: test_experiment_list_success (experiment.tests.views.test_experiment_views.ExperimentViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
experiment.models.Experiment.DoesNotExist: Experiment matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kimnam/git/work/pres/pres-paper/pres_note/experiment/tests/views/test_experiment_views.py", line 61, in setUp
    edited_by=self.user,
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/kimnam/git/work/pres/pres-paper/pres_note/experiment/models.py", line 66, in save
    super(Experiment,self).save(*args,**kwargs)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/db/models/base.py", line 803, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 179, in send
    for receiver in self._live_receivers(sender)
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/kimnam/git/work/pres/pres-paper/pres_note/experiment/signals.py", line 21, in wrapper
    signal_handler(*args, **kwargs)
  File "/Users/kimnam/git/work/pres/pres-paper/pres_note/experiment/signals.py", line 35, in experiment_history_insert_hundler
    history.save()
  File "/Users/kimnam/.pyenv/versions/pres36/lib/python3.6/site-packages/rest_framework/serializers.py", line 178, in save
    'You cannot call `.save()` on a serializer with invalid data.'
AssertionError: You cannot call `.save()` on a serializer with invalid data.

```

**Comment by t-itakura** [comment]
マージしたのでissueをクローズします
